type LangKey =
  | 'title' | 'saved' | 'placeholder' | 'visitBtn'
  | 'catSearch' | 'catVPN' | 'catBrowsers' | 'catMessengers'
  | 'catMarketplaces' | 'catWeather' | 'catDev' | 'catGov'
  | 'settings' | 'setCountry' | 'setCats' | 'setAuto'
  | 'onbTitle' | 'onbSub' | 'onbFinish'

type LangDict = Record<LangKey, string>

const I18N: Record<string, LangDict> = {
  en: { title:'Search engine',       saved:'✓ Saved',       placeholder:'Search...',     visitBtn:'Open',      catSearch:'Search',    catVPN:'VPN',  catBrowsers:'Browser',   catMessengers:'Chat',     catMarketplaces:'Market',  catWeather:'Weather', catDev:'Dev',   catGov:'Gov',    settings:'Settings',   setCountry:'Country',     setCats:'Categories',  setAuto:'Auto-detect', onbTitle:'Welcome!',              onbSub:'Pick your country & tabs', onbFinish:'Get started'  },
  ru: { title:'Поисковая система',   saved:'✓ Сохранено',   placeholder:'Поиск...',      visitBtn:'Открыть',   catSearch:'Поиск',     catVPN:'VPN',  catBrowsers:'Браузер',   catMessengers:'Чат',      catMarketplaces:'Магазин', catWeather:'Погода',  catDev:'Dev',   catGov:'Гос',    settings:'Настройки',  setCountry:'Страна',      setCats:'Категории',   setAuto:'Авто',        onbTitle:'Добро пожаловать!',     onbSub:'Выберите страну и разделы', onbFinish:'Начать'      },
  uk: { title:'Пошукова система',    saved:'✓ Збережено',   placeholder:'Пошук...',      visitBtn:'Відкрити',  catSearch:'Пошук',     catVPN:'VPN',  catBrowsers:'Браузер',   catMessengers:'Чат',      catMarketplaces:'Магазин', catWeather:'Погода',  catDev:'Dev',   catGov:'Держ',   settings:'Налашт.',    setCountry:'Країна',      setCats:'Категорії',   setAuto:'Авто',        onbTitle:'Ласкаво просимо!',      onbSub:'Оберіть країну та розділи', onbFinish:'Почати'     },
  de: { title:'Suchmaschine',        saved:'✓ Gespeichert', placeholder:'Suchen...',     visitBtn:'Öffnen',    catSearch:'Suche',     catVPN:'VPN',  catBrowsers:'Browser',   catMessengers:'Chat',     catMarketplaces:'Markt',   catWeather:'Wetter',  catDev:'Dev',   catGov:'Staat',  settings:'Einstellungen',setCountry:'Land',        setCats:'Kategorien',  setAuto:'Auto',        onbTitle:'Willkommen!',           onbSub:'Land und Bereiche wählen', onbFinish:'Loslegen'    },
  fr: { title:'Moteur de recherche', saved:'✓ Enregistré',  placeholder:'Rechercher...', visitBtn:'Ouvrir',    catSearch:'Recherche', catVPN:'VPN',  catBrowsers:'Navigateur',catMessengers:'Chat',     catMarketplaces:'Marché',  catWeather:'Météo',   catDev:'Dev',   catGov:'État',   settings:'Paramètres', setCountry:'Pays',        setCats:'Catégories',  setAuto:'Auto',        onbTitle:'Bienvenue !',           onbSub:'Choisissez pays et onglets', onbFinish:'Commencer'  },
  es: { title:'Motor de búsqueda',   saved:'✓ Guardado',    placeholder:'Buscar...',     visitBtn:'Abrir',     catSearch:'Búsqueda',  catVPN:'VPN',  catBrowsers:'Navegador', catMessengers:'Chat',     catMarketplaces:'Tienda',  catWeather:'Clima',   catDev:'Dev',   catGov:'Estado', settings:'Ajustes',    setCountry:'País',        setCats:'Categorías',  setAuto:'Auto',        onbTitle:'¡Bienvenido!',          onbSub:'Elige país y secciones',   onbFinish:'Empezar'     },
  pt: { title:'Motor de pesquisa',   saved:'✓ Salvo',       placeholder:'Pesquisar...',  visitBtn:'Abrir',     catSearch:'Pesquisa',  catVPN:'VPN',  catBrowsers:'Navegador', catMessengers:'Chat',     catMarketplaces:'Loja',    catWeather:'Tempo',   catDev:'Dev',   catGov:'Gov',    settings:'Configurar', setCountry:'País',        setCats:'Categorias',  setAuto:'Auto',        onbTitle:'Bem-vindo!',            onbSub:'Escolha país e seções',    onbFinish:'Começar'     },
  it: { title:'Motore di ricerca',   saved:'✓ Salvato',     placeholder:'Cerca...',      visitBtn:'Apri',      catSearch:'Ricerca',   catVPN:'VPN',  catBrowsers:'Browser',   catMessengers:'Chat',     catMarketplaces:'Negozio', catWeather:'Meteo',   catDev:'Dev',   catGov:'Stato',  settings:'Impostazioni',setCountry:'Paese',       setCats:'Categorie',   setAuto:'Auto',        onbTitle:'Benvenuto!',            onbSub:'Scegli paese e sezioni',   onbFinish:'Inizia'      },
  pl: { title:'Wyszukiwarka',        saved:'✓ Zapisano',    placeholder:'Szukaj...',     visitBtn:'Otwórz',    catSearch:'Szukaj',    catVPN:'VPN',  catBrowsers:'Przeglą.',  catMessengers:'Czat',     catMarketplaces:'Sklep',   catWeather:'Pogoda',  catDev:'Dev',   catGov:'Rząd',   settings:'Ustawienia', setCountry:'Kraj',        setCats:'Kategorie',   setAuto:'Auto',        onbTitle:'Witaj!',                onbSub:'Wybierz kraj i sekcje',    onbFinish:'Zacznij'     },
  nl: { title:'Zoekmachine',         saved:'✓ Opgeslagen',  placeholder:'Zoeken...',     visitBtn:'Openen',    catSearch:'Zoeken',    catVPN:'VPN',  catBrowsers:'Browser',   catMessengers:'Chat',     catMarketplaces:'Winkel',  catWeather:'Weer',    catDev:'Dev',   catGov:'Gov',    settings:'Instellingen',setCountry:'Land',        setCats:'Categorieën', setAuto:'Auto',        onbTitle:'Welkom!',               onbSub:'Kies land en secties',     onbFinish:'Begin'       },
  tr: { title:'Arama motoru',        saved:'✓ Kaydedildi',  placeholder:'Ara...',        visitBtn:'Aç',        catSearch:'Arama',     catVPN:'VPN',  catBrowsers:'Tarayıcı',  catMessengers:'Sohbet',   catMarketplaces:'Mağaza',  catWeather:'Hava',    catDev:'Dev',   catGov:'Devlet', settings:'Ayarlar',    setCountry:'Ülke',        setCats:'Kategoriler', setAuto:'Otomatik',    onbTitle:'Hoş geldiniz!',         onbSub:'Ülke ve bölüm seçin',     onbFinish:'Başla'       },
  zh: { title:'搜索引擎',             saved:'✓ 已保存',      placeholder:'搜索...',       visitBtn:'打开',      catSearch:'搜索',      catVPN:'VPN',  catBrowsers:'浏览器',    catMessengers:'聊天',    catMarketplaces:'商城',    catWeather:'天气',    catDev:'开发',  catGov:'政府',   settings:'设置',       setCountry:'国家',        setCats:'分类',        setAuto:'自动',        onbTitle:'欢迎！',                onbSub:'选择国家和分类',           onbFinish:'开始'        },
  ja: { title:'検索エンジン',         saved:'✓ 保存済み',    placeholder:'検索...',       visitBtn:'開く',      catSearch:'検索',      catVPN:'VPN',  catBrowsers:'ブラウザ',  catMessengers:'チャット', catMarketplaces:'ショップ', catWeather:'天気',   catDev:'開発',  catGov:'政府',   settings:'設定',       setCountry:'国',          setCats:'カテゴリ',    setAuto:'自動',        onbTitle:'ようこそ！',            onbSub:'国とタブを選択',           onbFinish:'はじめる'    },
  ko: { title:'검색 엔진',            saved:'✓ 저장됨',      placeholder:'검색...',       visitBtn:'열기',      catSearch:'검색',      catVPN:'VPN',  catBrowsers:'브라우저',  catMessengers:'채팅',     catMarketplaces:'쇼핑',    catWeather:'날씨',    catDev:'개발',  catGov:'정부',   settings:'설정',       setCountry:'국가',        setCats:'카테고리',    setAuto:'자동',        onbTitle:'환영합니다!',           onbSub:'국가 및 탭 선택',          onbFinish:'시작하기'    },
  ar: { title:'محرك البحث',          saved:'✓ تم الحفظ',    placeholder:'بحث...',        visitBtn:'فتح',       catSearch:'بحث',       catVPN:'VPN',  catBrowsers:'متصفح',    catMessengers:'دردشة',   catMarketplaces:'متجر',    catWeather:'طقس',     catDev:'تطوير',catGov:'حكومة',  settings:'الإعدادات',  setCountry:'البلد',       setCats:'الفئات',      setAuto:'تلقائي',      onbTitle:'مرحباً!',               onbSub:'اختر البلد والأقسام',     onbFinish:'ابدأ'        },
}

export function t(key: LangKey): string {
  const lang = navigator.language.slice(0, 2)
  return (I18N[lang] ?? I18N['en'])[key]
}
